In [1]:
from numpy import genfromtxt

In [2]:
product_data = genfromtxt('demo.csv', delimiter=',')

In [3]:
print(product_data)

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


In [4]:
import numpy as np

In [5]:
sample_array = np.asarray([[1,2,3], [4,5,6], [7,8,9]])

In [6]:
np.savetxt('my_first_demo.csv', sample_array, delimiter=",")

In [7]:
import pandas as pd

In [8]:
sample_df=pd.read_csv('demo.csv', sep=',', header=None)

In [9]:
sample_df.head()

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

In [13]:
sample_df.to_csv('demo_sample_df.csv', header=None, index=None)

In [19]:
df=pd.read_excel('employee.xlsx', sheet_name ='performance')

In [20]:
df.head()

name  performance_score
0    Allen Smith                723
1        S Kumar                520
2    Jack Morgan                674
3      Ying Chin                556
4  Dheeraj Patel                711

In [22]:
df.to_excel('employee_performance.xlsx', index=None)

In [23]:
emp_df = pd.read_excel('employee.xlsx', sheet_name='employee_details')

In [24]:
emp_df

name   age   income gender  department grade
0    Allen Smith  45.0      NaN    NaN  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3
6   James Authur  54.0      NaN      F  Operations    G3
7     Josh Wills  54.0  52000.0      F     Finance    G3
8       Leo Duck  23.0  98000.0      M       Sales    G4

In [27]:
with pd.ExcelWriter('new_employee_details.xlsx') as writer:
    emp_df.to_excel(writer, sheet_name='employee', index = None)
    df.to_excel(writer, sheet_name='performance', index = None)

In [28]:
df

name  performance_score
0    Allen Smith                723
1        S Kumar                520
2    Jack Morgan                674
3      Ying Chin                556
4  Dheeraj Patel                711
5  Satyam Sharma                649
6   James Authur                 53
7     Josh Wills                901
8       Leo Duck                709

In [30]:
for name in df['name']:
    print(name)

Allen Smith
S Kumar
Jack Morgan
Ying Chin
Dheeraj Patel
Satyam Sharma
James Authur
Josh Wills
Leo Duck


In [32]:
for score in df['performance_score']:
    print(score)

723
520
674
556
711
649
53
901
709


In [35]:
df=pd.read_json('employee.json')

In [36]:
df.head()

name   age   income gender  department grade
0    Allen Smith  45.0      NaN   None  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2

In [37]:
df.to_json('employee_demo.json', orient='columns')

In [42]:
df

name   age   income gender  department grade
0    Allen Smith  45.0      NaN   None  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2
5  Satyam Sharma   NaN  62000.0   None       Sales    G3
6   James Authur  54.0      NaN      F  Operations    G3
7     Josh Wills  54.0  52000.0      F     Finance    G3
8       Leo Duck  23.0  98000.0      M       Sales    G4

In [41]:
df.describe()

age        income
count   7.000000      7.000000
mean   40.428571  52857.142857
std    12.204605  26028.372797
min    23.000000  16000.000000
25%    31.000000  38500.000000
50%    45.000000  52000.000000
75%    49.500000  63500.000000
max    54.000000  98000.000000

In [46]:
df.groupby('department').mean()

age        income
department                    
Finance     43.0  34333.333333
Operations  43.0  42000.000000
Sales       34.0  75000.000000

In [45]:
df['age'].sum()

283.0